version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.14
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.2.2
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-backgrounds"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
    - 6.2.8
  - dependency-name: snyk
    versions:
    - 1.437.4
    - 1.446.0
    - 1.458.0
    - 1.463.0
    - 1.476.0
    - 1.487.0
    - 1.503.0
    - 1.512.0
    - 1.522.0
    - 1.531.0
    - 1.554.0
  - dependency-name: acorn
    versions:
    - 8.0.5
    - 8.1.0
    - 8.1.1
  - dependency-name: rollup
    versions:
    - 1.32.1
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.8
    - 5.11.9
  - dependency-name: semantic-release
    versions:
    - 17.3.3
    - 17.3.7
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
    - 17.0.3
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
